import axios from 'axios';
import FormData from 'form-data';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables from backend/.env
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const PINTEREST_ACCESS_TOKEN = process.env.PINTEREST_ACCESS_TOKEN;

if (!PINTEREST_ACCESS_TOKEN || PINTEREST_ACCESS_TOKEN === '...' || PINTEREST_ACCESS_TOKEN === '') {
  console.error('❌ PINTEREST_ACCESS_TOKEN is missing from your .env file.');
  console.error('Please add it to backend/.env like this: PINTEREST_ACCESS_TOKEN=your_token');
  process.exit(1);
}

const PINTEREST_API_BASE = 'https://api.pinterest.com/v5';

// Headers for Pinterest API requests
const headers = {
  Authorization: `Bearer ${PINTEREST_ACCESS_TOKEN}`,
  'Content-Type': 'application/json',
};

async function verifyPinterest() {
  console.log('─── Starting Pinterest Verification ───\n');

  try {
    // 1. Fetch User Account Details
    console.log('1. Fetching User Account...');
    try {
      const userRes = await axios.get(`${PINTEREST_API_BASE}/user_account`, { headers });
      const user = userRes.data;
      console.log(`✅ User verified: ${user.username} (ID: ${user.account_type})`);
      console.log(`   Profile: ${user.profile_url}`);
    } catch (userErr: any) {
      console.warn('⚠️ Could not fetch user_account (Consumer type error or scope issue). Continuing to boards...');
      if (userErr.response) console.warn(`   Error: ${userErr.response.data?.message || userErr.message}`);
    }

    // 2. Fetch Available Boards
    console.log('\n2. Fetching Boards...');
    const boardsRes = await axios.get(`${PINTEREST_API_BASE}/boards`, { headers });
    const boards = boardsRes.data.items;
    
    if (boards.length === 0) {
      console.error('❌ No boards found. Please create a board on Pinterest first.');
      process.exit(1);
    }
    
    console.log(`✅ Found ${boards.length} boards.`);
    boards.forEach((b: any) => console.log(`   - ${b.name} (ID: ${b.id})`));
    
    const targetBoardId = boards[0].id;
    console.log(`\nUsing board "${boards[0].name}" for testing...`);

    // 3. Create a Test Image Pin
    console.log('\n3. Creating Test Image Pin...');
    const testImageUrl = 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80';
    const imagePinPayload = {
      board_id: targetBoardId,
      title: 'Wedora Test Image Pin',
      description: 'This is an automated test pin generated by Wedora.',
      media_source: {
        source_type: 'image_url',
        url: testImageUrl
      }
    };

    const imagePinRes = await axios.post(`${PINTEREST_API_BASE}/pins`, imagePinPayload, { headers });
    console.log(`✅ Image Pin created successfully!`);
    console.log(`   Pin ID: ${imagePinRes.data.id}`);
    console.log(`   URL: https://www.pinterest.com/pin/${imagePinRes.data.id}/`);

    // 4. Create a Test Video Pin
    console.log('\n4. Creating Test Video Pin...');
    const testVideoUrl = 'https://www.w3schools.com/html/mov_bbb.mp4';
    
    // Step 4a: Register Video Upload
    console.log('   a. Registering media upload...');
    const registerRes = await axios.post(`${PINTEREST_API_BASE}/media`, 
      { media_type: 'video' },
      { headers }
    );
    const mediaId = registerRes.data.media_id;
    const uploadUrl = registerRes.data.upload_url;
    const uploadParameters = registerRes.data.upload_parameters;
    console.log(`      Media ID: ${mediaId}`);

    // Step 4b: Download video and upload to S3
    console.log('   b. Downloading video and uploading to Pinterest S3...');
    const videoStreamRes = await axios.get(testVideoUrl, { responseType: 'stream' });
    const form = new FormData();
    for (const [key, value] of Object.entries(uploadParameters)) {
      form.append(key, value as string);
    }
    form.append('file', videoStreamRes.data, { filename: 'video.mp4', contentType: 'video/mp4' });
    
    await axios.post(uploadUrl, form, {
      headers: form.getHeaders(),
      maxBodyLength: Infinity,
      maxContentLength: Infinity
    });
    console.log('      Upload complete.');

    // Step 4c: Poll Status
    console.log('   c. Polling for media processing status...');
    let isReady = false;
    let attempts = 0;
    while (!isReady && attempts < 30) {
      attempts++;
      const statusRes = await axios.get(`${PINTEREST_API_BASE}/media/${mediaId}`, { headers });
      const status = statusRes.data.status;
      console.log(`      Attempt ${attempts}: ${status}`);
      if (status === 'succeeded') {
        isReady = true;
      } else if (status === 'failed') {
        throw new Error('Video processing failed on Pinterest side.');
      } else {
        await new Promise(r => setTimeout(r, 5000));
      }
    }

    if (!isReady) throw new Error('Video processing timed out.');

    // Step 4d: Create the Pin
    console.log('   d. Creating the Video Pin...');
    const videoPinPayload = {
      board_id: targetBoardId,
      title: 'Wedora Test Video Pin',
      description: 'This is an automated test video pin generated by Wedora.',
      media_source: {
        source_type: 'video_id',
        cover_image_url: testImageUrl,
        media_id: mediaId
      }
    };
    
    const videoPinRes = await axios.post(`${PINTEREST_API_BASE}/pins`, videoPinPayload, { headers });
    console.log(`✅ Video Pin created successfully!`);
    console.log(`   Pin ID: ${videoPinRes.data.id}`);
    console.log(`   URL: https://www.pinterest.com/pin/${videoPinRes.data.id}/`);

    console.log('\n🎉 All Pinterest API verifications passed!');
  } catch (err: any) {
    console.error('\n❌ Verification Failed:');
    if (err.response) {
      console.error(`Status: ${err.response.status}`);
      console.error(JSON.stringify(err.response.data, null, 2));
    } else {
      console.error(err.message);
    }
  }
}

verifyPinterest();
