import axios, { AxiosInstance } from 'axios';
import { VideoMetadata } from './ffprobe.service';
import { EditPlan, validateEditPlan } from '../schemas/editPlan';

export class EditPlanService {
  private client: AxiosInstance;
  private model: string;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error('GROQ_API_KEY not set in environment');
    }
    this.model = process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile';
    this.client = axios.create({
      baseURL: 'https://api.groq.com/openai/v1',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      timeout: 60_000, 
    });
  }

  public async generateEditPlan(metadata: VideoMetadata, editPreferences: any): Promise<EditPlan> {
    // Extract overlay texts for the LLM (these are the ONLY texts that should appear in the video)
    const overlayTexts: any[] = Array.isArray(editPreferences?.overlayTexts) ? editPreferences.overlayTexts : [];
    
    // Footer config is passed through directly, NOT generated by the LLM
    const showFooter = editPreferences?.showFooter !== false;
    const footerText = editPreferences?.footerText || '@ai.for.weddings\n9821640951';

    const systemPrompt = `You are a strict FFmpeg EditPlan JSON generator.
Your job is to read video metadata and user editing preferences, and output a valid JSON object matching this EditPlan schema exactly:

{
  "version": "3.0",
  "editingStyle": "standard",
  "editingIntensity": "low" | "medium" | "high",
  "transitionStyle": "none" | "fade" | "slide" | "zoom",
  "cutFrequency": "slow" | "normal" | "fast",
  "aspectRatio": "16:9" | "9:16" | "1:1" | "original",
  "trimStrategy": {
    "enabled": false,
    "startTime": 0,
    "endTime": 0
  },
  "overlays": [
    {
      "text": "string",
      "startTime": 0,
      "endTime": 0,
      "position": "top" | "center" | "bottom",
      "placement": "video" | "header"
    }
  ],
  "renderSettings": {
    "resolution": "1080p",
    "fps": 30,
    "format": "mp4"
  }
}

CRITICAL RULES:
1. The "overlays" array must contain ONLY the user-provided overlay texts listed below. Do NOT invent, add, or generate any additional text overlays.
2. Do NOT render "purpose", "focusArea", "style", "intensity", or any other planning field as visible text in the video. Those are editing strategy inputs ONLY.
3. If the user provided overlay texts without start/end times, YOU must calculate appropriate, non-overlapping startTime and endTime values to stagger them throughout the video based on the video duration.
4. If the user requested "ai_decide" for placement, prefer "video" placement to maximize video presence. Only use "header" if readability absolutely requires it.
5. If no overlay texts are provided, set "overlays" to an empty array [].
6. Do NOT include "showFooter" or "footerText" in your output — those are handled separately.

Ensure all times are within the video duration.
Respond ONLY with raw JSON, no markdown, no explanation.`;

    const userPrompt = `
Video Metadata:
Duration: ${metadata.duration}s
Resolution: ${metadata.width}x${metadata.height}
FPS: ${metadata.fps}

Editing Strategy (DO NOT render these as text — use only to influence editing decisions):
- Style: ${editPreferences?.style || 'AI Decide'}
- Intensity: ${editPreferences?.intensity || 'AI Decide'}
- Focus Area: ${editPreferences?.focusArea || 'AI Decide'}
- Purpose: ${editPreferences?.purpose || 'AI Decide'}

User-Provided Overlay Texts (render ONLY these as visible text):
${overlayTexts.length > 0 ? JSON.stringify(overlayTexts, null, 2) : 'None — do NOT generate any overlay text.'}
    `;

    try {
      const response = await this.client.post('/chat/completions', {
        model: this.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.2,
        response_format: { type: "json_object" }
      });

      const content = response.data.choices[0]?.message?.content;
      if (!content) throw new Error('No content from Groq');

      const jsonString = content.replace(/```json/g, '').replace(/```/g, '').trim();
      const rawData = JSON.parse(jsonString);
      
      // Inject footer settings directly — do NOT rely on LLM to generate these
      rawData.showFooter = showFooter;
      rawData.footerText = footerText;
      
      return validateEditPlan(rawData);
    } catch (err) {
      console.error('Groq EditPlan Error:', err);
      throw err;
    }
  }
}
