import axios, { AxiosInstance } from 'axios';

export interface CreativeInput {
  /** Vision metadata generated by Qwen2‑VL */
  metadata: any;
  /** Free‑form user context (e.g., "I want a romantic vibe") */
  userContext: string;
  /** Target platform – influences hashtag style, caption length, etc. */
  platform: string;
}

export interface CreativeOutput {
  overlayText: string[];          // Text that will appear on‑screen
  hooks: string[];               // Opening hook lines
  captions: string[];            // Full caption for the post
  hashtags: string[];            // Platform‑ready hashtags (include #)
  templateId: string;            // Selected FFmpeg template (cinematic-fade, …)
  cinematicDirections: string[]; // High‑level directions for further processing
  editingStyle: string;
  pacingSuggestions: string;
  reelHook: string;
}

export class GroqService {
  private client: AxiosInstance;
  private model: string;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error('GROQ_API_KEY not set in environment');
    }
    // Using Llama-3.3-70b as requested for higher reasoning quality
    this.model = process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile';
    this.client = axios.create({
      baseURL: 'https://api.groq.com/openai/v1',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      timeout: 120_000, 
    });
  }

private buildPrompt(input: CreativeInput): string {
  const { metadata, userContext, platform } = input;

  return `You are a luxury wedding marketing creative director for an AI wedding planning company.

Your goal is NOT to create sentimental wedding captions.

Your goal is to generate promotional wedding marketing content that helps attract potential clients for wedding planning services.

Project Intelligence:

Vision Analysis:
${JSON.stringify(metadata, null, 2)}

User Context:
${userContext}

Target Platform:
${platform}

Generate a single JSON object (no markdown, no explanation) with this exact shape:

{
  "overlayText": ["<line>", "<line>"],
  "hooks": ["<hook>"],
  "captions": ["<caption>"],
  "hashtags": ["#tag1", "#tag2"],
  "templateId": "<chosen-template>",
  "cinematicDirections": ["<direction list>"],
  "editingStyle": "<style description>",
  "pacingSuggestions": "<pacing description>",
  "reelHook": "<reel hook>"
}

OverlayText Rules:
- Generate exactly 4 overlayText entries.
- Each overlay must be 2-5 words only.
- Maximum 25 characters.
- Must sound like premium advertising headlines.
- Focus on wedding venues, mandaps, decor, destinations, planning and luxury experiences.
- Avoid emotional storytelling.

NEVER generate:
- Love Story
- Eternal Vows
- Forever Begins
- Happily Ever After
- Soulmates
- Royal Wedding
- Our Journey

GOOD examples:
- Your Dream Wedding
- Luxury Mandaps Await
- Crafted For You
- Celebrate In Grandeur
- Dream Wedding Venues
- Destination Dreams Delivered
- Elegant Wedding Experiences
- Weddings Made Effortless
- Designed Around You
- Plan Beyond Expectations

Additional Constraints:
- Keep other strings under 100 characters.
- Follow platform-specific best practices.
- Choose templateId strictly from:
  [cinematic-fade, moody-slow, energetic-cut, default-template]
- cinematicDirections must include editing keywords such as zoom, pan, blur, color tone, transition.
- Return ONLY valid JSON.
`;
}

  private getDefaultOutput(): CreativeOutput {
    return {
      overlayText: ['Your Dream Wedding', "Designed Around You"],
      hooks: ["Wait for it..."],
      captions: ["Celebrating love and unforgettable memories."],
      hashtags: ["#wedding", "#love", "#cinematic"],
      templateId: 'default-template',
      cinematicDirections: [],
      editingStyle: "Cinematic Default",
      pacingSuggestions: "Slow and emotional",
      reelHook: "Watch this magical moment"
    };
  }

  async generate(input: CreativeInput, retries = 2): Promise<CreativeOutput> {
    const prompt = this.buildPrompt(input);
    const payload = {
      model: this.model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 1024,
      top_p: 1,
      stream: false,
    };

    for (let i = 0; i <= retries; i++) {
      try {
        const response = await this.client.post('/chat/completions', payload);
        const raw = response.data?.choices?.[0]?.message?.content?.trim();
        if (!raw) throw new Error('Empty response from Groq');

        // Extract JSON robustly
        const jsonStart = raw.indexOf('{');
        const jsonEnd = raw.lastIndexOf('}');
        if (jsonStart === -1 || jsonEnd === -1) {
          throw new Error('No JSON object found in response');
        }
        
        const jsonText = raw.substring(jsonStart, jsonEnd + 1);
        const parsed = JSON.parse(jsonText) as Partial<CreativeOutput>;

        // Basic Schema Validation
        return {
          overlayText: Array.isArray(parsed.overlayText) ? parsed.overlayText : this.getDefaultOutput().overlayText,
          hooks: Array.isArray(parsed.hooks) ? parsed.hooks : this.getDefaultOutput().hooks,
          captions: Array.isArray(parsed.captions) ? parsed.captions : this.getDefaultOutput().captions,
          hashtags: Array.isArray(parsed.hashtags) ? parsed.hashtags : this.getDefaultOutput().hashtags,
          templateId: typeof parsed.templateId === 'string' ? parsed.templateId : this.getDefaultOutput().templateId,
          cinematicDirections: Array.isArray(parsed.cinematicDirections) ? parsed.cinematicDirections : this.getDefaultOutput().cinematicDirections,
          editingStyle: typeof parsed.editingStyle === 'string' ? parsed.editingStyle : this.getDefaultOutput().editingStyle,
          pacingSuggestions: typeof parsed.pacingSuggestions === 'string' ? parsed.pacingSuggestions : this.getDefaultOutput().pacingSuggestions,
          reelHook: typeof parsed.reelHook === 'string' ? parsed.reelHook : this.getDefaultOutput().reelHook,
        };

      } catch (err: any) {
        console.error(`[GroqService] Generation failed on attempt ${i + 1}/${retries + 1}`);
        console.error('[GroqService] Error Details:', err.response?.data || err.message);
        
        if (i === retries) {
          console.error('[GroqService] Max retries reached. Returning graceful fallback JSON.');
          console.error('[GroqService] Failed Payload:', JSON.stringify(payload, null, 2));
          return this.getDefaultOutput();
        }
        // Wait before retry
        await new Promise(res => setTimeout(res, 2000 * (i + 1)));
      }
    }
    
    return this.getDefaultOutput();
  }
}
