import axios, { AxiosInstance } from 'axios';

export interface CreativeInput {
  /** Vision metadata generated by Qwen2‑VL */
  metadata: any;
  /** Free‑form user context (e.g., "I want a romantic vibe") */
  userContext: string;
  /** Target platform – influences hashtag style, caption length, etc. */
  platform: string;
}

export interface CreativeOutput {
  overlayText: string[];          // Text that will appear on‑screen
  hooks: string[];               // Opening hook lines
  captions: string[];            // Full caption for the post
  hashtags: string[];            // Platform‑ready hashtags (include #)
  cinematicDirections: string[]; // High‑level directions for further processing
  editingStyle: string;
  pacingSuggestions: string;
  reelHook: string;
  title?: string;
  description?: string;
  tags?: string[];
}

export class GroqService {
  private client: AxiosInstance;
  private model: string;

  constructor() {
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error('GROQ_API_KEY not set in environment');
    }
    // Using Llama-3.3-70b as requested for higher reasoning quality
    this.model = process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile';
    this.client = axios.create({
      baseURL: 'https://api.groq.com/openai/v1',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      timeout: 120_000, 
    });
  }

private buildPrompt(input: CreativeInput): string {
  const { metadata, userContext, platform } = input;

  let platformInstructions = '';
  if (platform === 'YOUTUBE') {
    platformInstructions = `
Additional Fields for YouTube:
- "title": A catchy, SEO-optimized title (max 100 chars).
- "description": A longer description (up to 5,000 chars) that includes keywords.
- "tags": Array of comma-separated tag strings (e.g., ["scenery", "event"]).
`;
  }

  return `You are a luxury wedding marketing creative director for an AI wedding planning company.

Your goal is to generate promotional wedding marketing content that helps attract potential clients for wedding planning services, but you MUST anchor your marketing copy in the actual visual observations provided below. 
Do NOT generate generic, disconnected marketing phrases. Every piece of content should feel like premium wedding marketing, but it must be tailored specifically to the unique venue, decor, lighting, and colors detected in THIS video.

=== VISION ANALYSIS ===
${JSON.stringify(metadata, null, 2)}

=== USER INTENT ===
${userContext}

=== TARGET PLATFORM ===
${platform}

Generate a JSON object:
{
  "overlayText": [],
  "hooks": [],
  "captions": [],
  "hashtags": [],
  "cinematicDirections": [],
  "editingStyle": "",
  "pacingSuggestions": "",
  "reelHook": ""${platform === 'YOUTUBE' ? ',\n  "title": "<title>",\n  "description": "<description>",\n  "tags": ["<tag1>", "<tag2>"]' : ''}
}
${platformInstructions}

Rules:
- overlayText: 4 entries, 2-5 words each, max 25 chars. Must sound like premium advertising headlines BUT must incorporate or complement the specific detected visuals. GOOD examples(use this as an example dont copy this exact phrases): "Your Dream Mandap", "Destination Dreams", "Luxury Awaits You", "Elegant Outdoor Ceremonies".
- hooks: 1 entry. Must reference a specific visual detail from the video to catch the viewer's attention.
- captions: 1 entry. Must read like high-end wedding planning marketing, incorporating the detected venue, decor, or activities as proof of your service's quality.
- hashtags: 5-8 entries. Blend general wedding marketing tags (e.g., #WeddingPlanner, #LuxuryWedding) with at least 3 tags referencing detected elements (e.g., #OutdoorCeremony, #RedFloralDecor).
- cinematicDirections: 3-5 entries. Must reference detected camera movements and lighting.
- editingStyle: 1 sentence grounded in detected colors and lighting.
- pacingSuggestions: 1 sentence based on detected camera movements.
- reelHook: 1 sentence referencing a unique visual detail to keep them watching.

Do NOT repeat the exact same phrases across different videos. Vary your vocabulary while maintaining a premium, luxurious tone.
If visual information is limited, describe what IS visible to sell the moment, rather than inventing details.
Return ONLY valid JSON.
`;
}

  private getDefaultOutput(): CreativeOutput {
    return {
      overlayText: ['Your Dream Wedding', "Designed Around You", "Crafted To Perfection", "Unforgettable Details"],
      hooks: ["Wait until you see this venue..."],
      captions: ["Every detail of your big day meticulously planned to match your vision. We bring dream weddings to life."],
      hashtags: ["#LuxuryWedding", "#WeddingPlanner", "#DreamWedding"],
      cinematicDirections: [],
      editingStyle: "Premium and cinematic",
      pacingSuggestions: "Elegant and smooth",
      reelHook: "Experience the magic of this moment"
    };
  }

  async generate(input: CreativeInput, retries = 2): Promise<CreativeOutput> {
    const prompt = this.buildPrompt(input);
    const payload = {
      model: this.model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 1024,
      top_p: 1,
      stream: false,
    };

    for (let i = 0; i <= retries; i++) {
      try {
        const response = await this.client.post('/chat/completions', payload);
        const raw = response.data?.choices?.[0]?.message?.content?.trim();
        if (!raw) throw new Error('Empty response from Groq');

        // Extract JSON robustly
        const jsonStart = raw.indexOf('{');
        const jsonEnd = raw.lastIndexOf('}');
        if (jsonStart === -1 || jsonEnd === -1) {
          throw new Error('No JSON object found in response');
        }
        
        const jsonText = raw.substring(jsonStart, jsonEnd + 1);
        const parsed = JSON.parse(jsonText) as Partial<CreativeOutput>;

        // Basic Schema Validation
        return {
          overlayText: Array.isArray(parsed.overlayText) ? parsed.overlayText : this.getDefaultOutput().overlayText,
          hooks: Array.isArray(parsed.hooks) ? parsed.hooks : this.getDefaultOutput().hooks,
          captions: Array.isArray(parsed.captions) ? parsed.captions : this.getDefaultOutput().captions,
          hashtags: Array.isArray(parsed.hashtags) ? parsed.hashtags : this.getDefaultOutput().hashtags,
          cinematicDirections: Array.isArray(parsed.cinematicDirections) ? parsed.cinematicDirections : this.getDefaultOutput().cinematicDirections,
          editingStyle: typeof parsed.editingStyle === 'string' ? parsed.editingStyle : this.getDefaultOutput().editingStyle,
          pacingSuggestions: typeof parsed.pacingSuggestions === 'string' ? parsed.pacingSuggestions : this.getDefaultOutput().pacingSuggestions,
          reelHook: typeof parsed.reelHook === 'string' ? parsed.reelHook : this.getDefaultOutput().reelHook,
          title: typeof parsed.title === 'string' ? parsed.title : undefined,
          description: typeof parsed.description === 'string' ? parsed.description : undefined,
          tags: Array.isArray(parsed.tags) ? parsed.tags : undefined,
        };

      } catch (err: any) {
        console.error(`[GroqService] Generation failed on attempt ${i + 1}/${retries + 1}`);
        console.error('[GroqService] Error Details:', err.response?.data || err.message);
        
        if (i === retries) {
          console.error('[GroqService] Max retries reached. Returning graceful fallback JSON.');
          console.error('[GroqService] Failed Payload:', JSON.stringify(payload, null, 2));
          return this.getDefaultOutput();
        }
        // Wait before retry
        await new Promise(res => setTimeout(res, 2000 * (i + 1)));
      }
    }
    
    return this.getDefaultOutput();
  }
}
